spring:
  profiles:
    active: local

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/redia_restaurante}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:RediaRestauranteClaveUltraSecreta123456}
  expiration: 900000
  refresh-expiration: 604800000

google:
  client-id: ${GOOGLE_CLIENT_ID:115728163825-koff0lsutk5h271dlck8s23rnt37sq42.apps.googleusercontent.com}
  client-secret: ${GOOGLE_CLIENT_SECRET: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}

  recaptcha:
    enabled: true
    secret: ${RECAPTCHA_SECRET:6Lcg2IMsAAAAAOJC9s-bZ4RyVeTRdJAfZlSE9GpU}
    url: https://www.google.com/recaptcha/api/siteverify