spring:
  application:
    name: redia-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  security:
    user:
      name: ${PROM_USER:prometheus_scraper}
      password: ${PROM_PASS:change_me_in_production}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
  refresh-expiration: 604800000

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

  recaptcha:
    enabled: true
    secret: ${RECAPTCHA_SECRET}
    url: https://www.google.com/recaptcha/api/siteverify

# Configuración de Prometheus y Actuator para Grafana Cloud
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator

  endpoint:
    health:
      show-details: when-authorized
    prometheus:
      enabled: true

  health:
    db:
      enabled: false
    diskspace:
      enabled: false
    ping:
      enabled: true
    defaults:
      enabled: false

  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 1m
    tags:
      application: redia-backend
      environment: production

