name: Build and deploy JAR app to Azure Web App - redia-backend-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Ver JAR generado  # 👈 Agrega esto para ver el nombre exacto
        run: ls -la build/libs/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'  # 👈 Cambia a *.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Ver JAR descargado
        run: ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CDABA067DC83472D886725A5478ECC7C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A822A7F126124E55A20E0E83AF646264 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D7B590441013409BADF17DA1420CB02C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'redia-backend-2'
          slot-name: 'Production'
          package: '*.jar'